const Navigation = require('../controllers/NavigationController')
const headerContainer = document.getElementById("header-container")
const mainContainer = document.getElementById("main-container")
const navigationController = new Navigation(headerContainer, mainContainer)
navigationController.init()